config/routes.rb
Rails.application.routes.draw do
  resources :revenue do
    member do
      get :delete
    end

  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/revenue.rb
class Revenue < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/revenue_controller.rb
class RevenueController < ApplicationController
  def index
    @revenues = Revenue.all.order(:id)

    @total_revenue = @revenues.map{|r| r['amount']}.reduce(0, :+)
  end

  def show
   @revenue = Revenue.find(params[:id])
  end

  def new
    @revenue = Revenue.new
  end

  def create
    @revenue = Revenue.new(revenue_params)
    if @revenue.save
        redirect_to(revenue_index_path)
    else
      render('new')
    end
  end

  def edit
    @revenue = Revenue.find(params[:id])
  end

  def update
    @revenue = Revenue.find(params[:id])
    if @revenue.update_attributes(revenue_params)
        redirect_to(revenue_index_path)
    else
      render('new')
    end
  end
  def delete
    @revenue = Revenue.find(params[:id])
  end
  def destroy
    @revenue = Revenue.find(params[:id])
    @revenue.destroy
    redirect_to(revenue_index_path)
  end
  private
   def revenue_params
     params.require(:revenue).permit(:id,:description,:amount,:date,:typology)
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/revenue_helper.rb
module RevenueHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SsfAccounts</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-default">
        <a class="navbar-brand" href="">
          <img class="logo alt="Brand" src="http://www.sportsenzafrontiere.it/wp-content/themes/ssf/images/icons/sport-senza-frontiere.png">
        </a>
        <ul class="nav navbar-nav">
          <li><a href="#">Home</a></li>
          <li><a href="#">Dashboard</a></li>
          <li><a href="#">Costs</a></li>
          <li><a href="http://localhost:3000/revenue">Revenues</a></li>
        </ul>
        </nav>
      <%= yield %>
      </div>
  </body>
</html>

app/views/revenue/delete.html.erb
<h2>Delete Page</h2>

<p>sei sicuro che vuoi cancellare <%= @revenue.description %> ?</p>

<%= link_to "Delete", revenue_path, :method => "delete", :class => "btn btn-danger" %>

app/views/revenue/edit.html.erb
<h2 class="text-center">Edit revenue </h2>

<%= bootstrap_form_for(@revenue) do |f| %>

    <%= f.text_field :description %>
    <%= f.number_field :amount  %>
      <%= f.date_field :date  %>
      <%= f.select :typology,([['erogazione liberale'],['contributo']]) %>
    <%= f.submit "Update", class: "btn btn-success"%>

<% end %>

app/views/revenue/index.html.erb
<h2 class="text-center revenue-list">Revenues </h2>
<%= link_to "Add new revenue", new_revenue_path, :class => "btn btn-success" %>

<table class="table table-striped">
  <tr>
    <th>Description</th>
    <th>Amount €</th>
    <th>Date</th>
    <th>Tipology</th>
    <th>Show</th>
    <th>Delete</th>
  </tr>

  <% @revenues.each do |revenue| %>
    <tr>
      <td><%= revenue.description %></td>
      <td><%= revenue.amount %></td>
      <td><%= revenue.date  %></td>
      <td><%= revenue.typology %></td>
      <td><%= link_to "Show", revenue, :class => "btn btn-info" %></td>
      <td><%= link_to "Delete",delete_revenue_path(revenue),:class => "btn btn-danger" %></td>
    </tr>

  <% end %>
  <tr>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr class="total-revenue">
    <td>Total revenue</td>
    <td ><%= @total_revenue %></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
</table>

app/views/revenue/new.html.erb
<h2 class="text-center">Add revenue </h2>

<%= bootstrap_form_for @revenue, url: {action: "create"}, html: {class: "form"} do |f| %>

    <%= f.text_field :description %>
    <%= f.number_field :amount  %>
      <%= f.date_field :date  %>
      <%= f.select :typology,([['erogazione liberale'],['contributo']]) %>
    <%= f.submit "Submit", class: "btn btn-success"%>

<% end %>

app/views/revenue/show.html.erb
<div class="row">
  <div class="col-xs-3"></div>
  <div class="col-xs-6">
    <%= link_to "Edit revenue", edit_revenue_path, :class => "btn btn-primary edit-btn" %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Show Revenue n. <%= @revenue.id %> </h3>
      </div>
      <div class="panel-body">
        <p><%= @revenue.description %></p>
        <p><%= @revenue.amount %></p>
        <p><%= @revenue.typology %></p>
      </div>
    </div>
  </div>
  <div class="col-xs-3"></div>
</div>